import { ScanOutput, MigrationBlocker } from '@/lib/types';

export function generateMarkdownRunbook(scan: ScanOutput): string {
  const lines: string[] = [];

  // Header
  lines.push('# Salesforce Org Analysis Runbook');
  lines.push('');
  lines.push(`**Generated:** ${new Date(scan.scannedAt).toLocaleString()}`);
  lines.push(`**Scan Duration:** ${(scan.scanDuration / 1000).toFixed(1)}s`);
  lines.push('');

  // Org Info
  lines.push('## Organization Information');
  lines.push('');
  lines.push(`- **Org ID:** ${scan.orgInfo.id}`);
  lines.push(`- **Type:** ${scan.orgInfo.organizationType}`);
  lines.push(`- **Edition:** ${scan.orgInfo.edition}`);
  lines.push(`- **Instance:** ${scan.orgInfo.instanceName}`);
  lines.push(`- **Active Users:** ${scan.orgInfo.userCount.toLocaleString()}`);
  lines.push('');

  // Key Metrics
  lines.push('## Key Metrics');
  lines.push('');
  lines.push(`- **Objects:** ${scan.objects.length}`);
  lines.push(`- **Flows:** ${scan.flows.length}`);
  lines.push(`- **Triggers:** ${scan.triggers.length}`);
  lines.push(`- **Validation Rules:** ${scan.validationRules.length}`);
  lines.push(`- **Profiles:** ${scan.profiles.length}`);
  lines.push(`- **Roles:** ${scan.roles.length}`);
  lines.push(`- **Reports:** ${scan.reports.length}`);
  lines.push(`- **Dashboards:** ${scan.dashboards.length}`);
  lines.push('');

  // Top Objects by Record Count
  lines.push('## Top Objects by Record Count');
  lines.push('');
  const topObjects = scan.objects
    .sort((a, b) => b.recordCount - a.recordCount)
    .slice(0, 10);
  
  for (const obj of topObjects) {
    lines.push(`- **${obj.label}** (${obj.name}): ${obj.recordCount.toLocaleString()} records`);
  }
  lines.push('');

  // Migration Blockers
  lines.push('## Migration Blockers');
  lines.push('');
  
  if (scan.blockers.length === 0) {
    lines.push('✅ No critical migration blockers detected.');
  } else {
    const bySeverity = {
      high: scan.blockers.filter((b) => b.severity === 'high'),
      medium: scan.blockers.filter((b) => b.severity === 'medium'),
      low: scan.blockers.filter((b) => b.severity === 'low'),
    };

    if (bySeverity.high.length > 0) {
      lines.push('### 🔴 High Severity');
      lines.push('');
      for (const blocker of bySeverity.high) {
        lines.push(`#### ${blocker.type.toUpperCase()}`);
        if (blocker.object) {
          lines.push(`- **Object:** ${blocker.object}`);
        }
        lines.push(`- **Message:** ${blocker.message}`);
        lines.push(`- **Recommendation:** ${blocker.recommendation}`);
        lines.push('');
      }
    }

    if (bySeverity.medium.length > 0) {
      lines.push('### 🟡 Medium Severity');
      lines.push('');
      for (const blocker of bySeverity.medium) {
        lines.push(`#### ${blocker.type.toUpperCase()}`);
        if (blocker.object) {
          lines.push(`- **Object:** ${blocker.object}`);
        }
        lines.push(`- **Message:** ${blocker.message}`);
        lines.push(`- **Recommendation:** ${blocker.recommendation}`);
        lines.push('');
      }
    }

    if (bySeverity.low.length > 0) {
      lines.push('### 🟢 Low Severity');
      lines.push('');
      for (const blocker of bySeverity.low) {
        lines.push(`#### ${blocker.type.toUpperCase()}`);
        if (blocker.object) {
          lines.push(`- **Object:** ${blocker.object}`);
        }
        lines.push(`- **Message:** ${blocker.message}`);
        lines.push(`- **Recommendation:** ${blocker.recommendation}`);
        lines.push('');
      }
    }
  }
  lines.push('');

  // Automation Summary
  lines.push('## Automation Summary');
  lines.push('');
  lines.push('### Flows');
  for (const flow of scan.flows.slice(0, 20)) {
    lines.push(`- ${flow.label} (${flow.status})`);
  }
  if (scan.flows.length > 20) {
    lines.push(`... and ${scan.flows.length - 20} more`);
  }
  lines.push('');

  lines.push('### Triggers');
  const triggersByObject: Record<string, number> = {};
  for (const trigger of scan.triggers) {
    triggersByObject[trigger.object] = (triggersByObject[trigger.object] || 0) + 1;
  }
  for (const [object, count] of Object.entries(triggersByObject)) {
    lines.push(`- ${object}: ${count} trigger(s)`);
  }
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*This runbook was generated by Org Analyzer.*');

  return lines.join('\n');
}
